### PR TITLE
Implement redundant epsilon removing optimization

### PR DESCRIPTION
**Pull request by KvanTTT**
*Porting a PR from ANTLR4 repository (https://github.com/antlr/antlr4/pull/3676)*

* Introduced `RedundantEpsilonRemover` that performs the following ATN optimizations for `BasicState`:
  * Removing of single incoming epsilon transition
  * Removing of single outgoing epsilon transition with several incoming transitions
* Removed all optimizations from `ParserATNFactory` since they are useless, not fully correct and are performed on the separated optimization step
* Introduced `ATNOptimizerHelper` that do the following:
  * Calculates incoming transitions that are used in ATN optimizers
  * Tracks replacement of state that are being removed during optimization. Old states are being replaced on the new ones in the final step (`updateAstNodes`)
  * Compresses array of ATN states (removes null items after previous optimization steps, `compressStates`)
* Fixed the previous `ATNOptimizer` and renamed to `SetMerger`. Now it considers incoming transitions and `ATNOptimizerHelper` accurately tracks replacements.

Implemented optimizations decreases ATN especially for lexers and should improve performance for generated parsers because of decreased number of method calls. Also they don't affect runtime code except of interpreter part (that is buggy anyway).

### Input

single_incoming_output

### Output

<!-- ```graphviz
digraph single_incoming_output {
    rankdir=LR;
    node [shape = circle];

    I1 -> O1 [ label = "l" ]
}
``` -->

![single_incoming_output](https://user-images.githubusercontent.com/1150330/164895834-7d2b29aa-ec2e-4051-8e9b-4d06b1a64147.svg)

## Removing of single outgoing epsilon transition with several incoming transitions

### Input

<!-- ```graphviz
digraph finite_state_machine {
    rankdir=LR;
    node [shape = circle];

    I1 -> S [ label = "l1" ]
    I2 -> S [ label = "l2" ]
    I3 -> S [ label = "l3" ]
    S -> O1 [ label = "ε" ]
}
``` -->

![single_outgoing_input](https://user-images.githubusercontent.com/1150330/164895922-928a0afa-b687-43d8-97b7-69cc32162537.svg)

### Output

<!-- ```graphviz
digraph finite_state_machine {
    rankdir=LR;
    node [shape = circle];

    I1 -> O1 [ label = "l1" ]
    I2 -> O1 [ label = "l2" ]
    I3 -> O1 [ label = "l3" ]
}
``` -->

![single_outgoing_output](https://user-images.githubusercontent.com/1150330/164895930-224f9f64-51cf-4d5c-b30b-f5baeeb2c840.svg)

## Example

```g4
lexer grammar L;
A: 'A' 'B'+ (C | D) 'E';
fragment C: 'C';
fragment D: 'D';
```

### Old ATN

Number of states: **23**

<!-- ```graphviz
digraph old_atn {
rankdir=LR;
s2[fontsize=11, label="2", shape=doublecircle, fixedsize=true, width=.6];
s1[fontsize=11,label="1", shape=circle, fixedsize=true, width=.55, peripheries=1];
s7[fontsize=11,label="7", shape=circle, fixedsize=true, width=.55, peripheries=1];
s8[fontsize=11,label="8", shape=circle, fixedsize=true, width=.55, peripheries=1];
s9[fontsize=11,label="&rarr;\n9+", shape=circle, fixedsize=true, width=.55, peripheries=1];
s10[fontsize=11,label="&larr;\n10", shape=circle, fixedsize=true, width=.55, peripheries=1];
s11[fontsize=11,label="{11+\nd=1|{<p0>|<p1>}}", shape=record, fixedsize=false, peripheries=1];
s12[fontsize=11,label="12", shape=circle, fixedsize=true, width=.55, peripheries=1];
s13[fontsize=11,label="13", shape=circle, fixedsize=true, width=.55, peripheries=1];
s14[fontsize=11,label="14", shape=circle, fixedsize=true, width=.55, peripheries=1];
s15[fontsize=11,label="{&rarr;\n15\nd=2|{<p0>|<p1>}}", shape=record, fixedsize=false, peripheries=1];
s16[fontsize=11,label="&larr;\n16", shape=circle, fixedsize=true, width=.55, peripheries=1];
s17[fontsize=11,label="17", shape=circle, fixedsize=true, width=.55, peripheries=1];
s18[fontsize=11,label="18", shape=circle, fixedsize=true, width=.55, peripheries=1];
s1 -> s7 [fontname="Times-Italic", label="&epsilon;"];
s7 -> s9 [fontsize=11, fontname="Courier", arrowsize=.7, label = "'A'", arrowhead = normal];
s9 -> s8 [fontname="Times-Italic", label="&epsilon;"];
s8 -> s10 [fontsize=11, fontname="Courier", arrowsize=.7, label = "'B'", arrowhead = normal];
s10 -> s11 [fontname="Times-Italic", label="&epsilon;"];
s11:p0 -> s9 [fontname="Times-Italic", label="&epsilon;", style="dashed"];
s11:p1 -> s12 [fontname="Times-Italic", label="&epsilon;"];
s12 -> s15 [fontname="Times-Italic", label="&epsilon;"];
s15:p0 -> s13 [fontname="Times-Italic", label="&epsilon;"];
s15:p1 -> s14 [fontname="Times-Italic", label="&epsilon;"];
s13 -> s16 [fontsize=11, fontname="Courier", arrowsize=.7, label = "<C>", arrowhead = normal];
s14 -> s16 [fontsize=11, fontname="Courier", arrowsize=.7, label = "<D>", arrowhead = normal];
s16 -> s17 [fontname="Times-Italic", label="&epsilon;"];
s17 -> s18 [fontsize=11, fontname="Courier", arrowsize=.7, label = "'E'", arrowhead = normal];
s18 -> s2 [fontname="Times-Italic", label="&epsilon;"];
}
``` -->

![old_atn](https://user-images.githubusercontent.com/1150330/164895941-773f10f3-7df4-4860-b2cc-e5367223bda3.svg)

### New ATN

Number of states: **15**

<!-- ```graphviz
digraph new_atn {
rankdir=LR;
s2[fontsize=11, label="2", shape=doublecircle, fixedsize=true, width=.6];
s1[fontsize=11,label="1", shape=circle, fixedsize=true, width=.55, peripheries=1];
s7[fontsize=11,label="&rarr;\n7+", shape=circle, fixedsize=true, width=.55, peripheries=1];
s8[fontsize=11,label="&larr;\n8", shape=circle, fixedsize=true, width=.55, peripheries=1];
s9[fontsize=11,label="{9+\nd=1|{<p0>|<p1>}}", shape=record, fixedsize=false, peripheries=1];
s10[fontsize=11,label="10", shape=circle, fixedsize=true, width=.55, peripheries=1];
s11[fontsize=11,label="11", shape=circle, fixedsize=true, width=.55, peripheries=1];
s12[fontsize=11,label="12", shape=circle, fixedsize=true, width=.55, peripheries=1];
s13[fontsize=11,label="{&rarr;\n13\nd=2|{<p0>|<p1>}}", shape=record, fixedsize=false, peripheries=1];
s14[fontsize=11,label="&larr;\n14", shape=circle, fixedsize=true, width=.55, peripheries=1];
s1 -> s7 [fontsize=11, fontname="Courier", arrowsize=.7, label = "'A'", arrowhead = normal];
s7 -> s8 [fontsize=11, fontname="Courier", arrowsize=.7, label = "'B'", arrowhead = normal];
s8 -> s9 [fontname="Times-Italic", label="&epsilon;"];
s9:p0 -> s7 [fontname="Times-Italic", label="&epsilon;", style="dashed"];
s9:p1 -> s10 [fontname="Times-Italic", label="&epsilon;"];
s10 -> s13 [fontname="Times-Italic", label="&epsilon;"];
s13:p0 -> s11 [fontname="Times-Italic", label="&epsilon;"];
s13:p1 -> s12 [fontname="Times-Italic", label="&epsilon;"];
s11 -> s14 [fontsize=11, fontname="Courier", arrowsize=.7, label = "<C>", arrowhead = normal];
s12 -> s14 [fontsize=11, fontname="Courier", arrowsize=.7, label = "<D>", arrowhead = normal];
s14 -> s2 [fontsize=11, fontname="Courier", arrowsize=.7, label = "'E'", arrowhead = normal];
}
``` -->

![new_atn](https://user-images.githubusercontent.com/1150330/164896436-ac3b3c0f-cf5a-4986-80d4-aa642ca24a63.svg)


## Plans

It looks like `BlockEndState` (8, 14), `LoopEndState` (10) can be also safely removed in the same way since they are not used in decisions. But it might require small changes in runtimes.

### CODE REVIEW

**Comment by ericvergnaud** [comment]
Hey, thanks for this.
I have 2 concerns:
 - these changes apply to the Java runtime, which is going away in favor of the Kotlin runtime
 - do we have a benchmark demonstrating that this change does improve performance ?

**Comment by KvanTTT** [comment]
> these changes apply to the Java runtime, which is going away in favor of the Kotlin runtime

The changes in runtime are small and not-functional, they can be easily ported to Kotlin later. The PR is mostly about improving the tool (ATN generation). The tool is currently written in Java.

> do we have a benchmark demonstrating that this change does improve performance ?

Yes, you can explore the thread in the original PR, specifically this comment and later: https://github.com/antlr/antlr4/pull/3676#issuecomment-1116050463

**Comment by ericvergnaud** [comment]
Ok then I'd suggest updating Kotlin code accordingly as part of this PR, otherwise it's going to be very messy when I drop the Java runtime ?

**Comment by KvanTTT** [comment]
> Ok then I'd suggest updating Kotli n code accordingly as part of this PR ?

I suggest postponing it since tool currently doesn't rely on Kotlin runtime and it anyway requires a lot of fixes and maybe even modules splitting.

I'm suggesting this PR now because it's already ready and if I decide to suggest it after moving to Kotlin runtime, I'll encountered a lot of conflicts and rewriting code to Kotlin, it's not very productive.

**Comment by ericvergnaud** [comment]
Need to do Kotlin part rapidly, see issue #39

**Pull request merged**
