### PR TITLE
Updating documentations for ANTLR 5

### PR DESCRIPTION
**Pull request by ftomassetti**
This PR does a combination of minor things to update references to ANTLR4 into references to ANTLR5.

* It updates information on contributing, specifying that from the beginning ANTLR 5 is using the DCO mechanism and removing the historical contribution agreement
* remove the changelog file, not been updated since 2014
* remove several files documenting dropped targets
* update the document on releasing ANTLR very coarsely, by removing paragraphs about dropped targets and changing the references to ANTLR 4 into references to ANTLR 5

Moved to the #26 instead:
* It renames Antlr4MojoTest into Antlr5MojoTest
* from POM, remove the configuration for cleaning the swift target, as it has been dropped

### CODE REVIEW

**Review by ericvergnaud — CHANGES_REQUESTED** [review]
Can we have separate PRs for code changes and doc changes ?

**Comment by ftomassetti** [comment]
> Can we have separate PRs for code changes and doc changes ?

Sure, I extracted #26 to focus on code and infrastructure, and I have updated this PR to focus exclusively on documentation

**Comment by ftomassetti** [comment]
In this case, after I performed the changes requested, should I press the button `Re-request review` or is it enough to add a comment in the PR?

**Comment by ericvergnaud** [comment]
> In this case, after I performed the changes requested, should I press the button `Re-request review` or is it enough to add a comment in the PR?

I guess the former expresses clearly that from your POV it is ready ?

**Comment by ericvergnaud** [comment]
Plus technically I think it triggers a review workflow, which maybe helps close the previous review. Let's find out ?

**Comment by ftomassetti** [comment]
Thanks, I pressed the button

**Review by ericvergnaud — APPROVED** [review]

**Comment by ericvergnaud** [comment]
It does help close the previous review 😄

**Pull request merged**
