### PR TITLE
Reorganizing packages inherited from ANTLR Kotlin

### PR DESCRIPTION
**Pull request by ftomassetti**
This PR completes the restructuring of code inherited from ANTLR Kotlin doing two things:
- It reorganizes all packages under com.strumenta to fall under org.antlr.v5
- It rename the unused targets of ANTLR Kotlin into antlr-kotlin-runtime-remnants, adding a README in that directory to explain why they are kept around

Replace #15 and complete #14

### CODE REVIEW

**Comment by lppedd** [comment]
Do we need to keep `kotlinruntime` as package name? 
At this point I'd just use `runtime`, since we know we're sticking with Kotlin.

Minor detail tho, up to you all.

**Comment by KvanTTT** [comment]
> Do we need to keep kotlinruntime as package name? At this point I'd just use runtime, since we know we're sticking with Kotlin.

It seems redundant but we still have Java runtime and we have to distinguish packages from these runtimes in some way for tests infrastructure. I think we should rename `kotlinruntime` anyway but I'm not sure how.

**Comment by ericvergnaud** [comment]
The naming ayatollah sleeping not too deeply within my reptile brain would suggest the following folder naming rules:
 - common root: org/antlr/v5
 - followed by component: tool, runtime, maven, ...
 - followed when it makes sense by the target language: java, kotlin, typescript...
As we all know, for any JVM language this defines the package name.
So in the above example `kotlinruntime` would become `runtime/kotlin`

**Comment by ftomassetti** [comment]
I have updated the package names following the suggestions by Eric

**Review by KvanTTT — CHANGES_REQUESTED** [review]
I suggest moving from `jvm.org.antlr.v4.runtime.kotlin` to `org.antlr.v4.runtime.kotlin.jvm` and changing packages inside this directory (`package org.antlr.v5.runtime.kotlin` -> `org.antlr.v4.runtime.kotlin.jvm`).

Ideally, we should fix all `Package directive does not match the file location` warnings (currently they exist for files inside `jvm.org.antlr.v4.runtime.kotlin`).

**Comment by ericvergnaud** [comment]
> I suggest moving from `jvm.org.antlr.v4.runtime.kotlin` to `org.antlr.v4.runtime.kotlin.jvm` and changing packages inside this directory (`package org.antlr.v5.runtime.kotlin` -> `org.antlr.v4.runtime.kotlin.jvm`).
> 
> Ideally, we should fix all `Package directive does not match the file location` warnings (currently they exist for files inside `jvm.org.antlr.v4.runtime.kotlin`).

Well the package itself is `org.antlr.v4.runtime.kotlin` which I think is fine.
We'd need to understand why this sits under `src/jvm` rather than directly under `src` ?

**Comment by KvanTTT** [comment]
> Well the package itself is org.antlr.v4.runtime.kotlin which I think is fine.

Not completely. Currently it doesn't matter a lot because packages will be reorginized when we implement KMP, but there is rule of good manners to keep in sync package name and directory structure and to get rid of `Package directive does not match the file location` warnings.

> We'd need to understand why this sits under src/jvm rather than directly under src ?

It helps us to separate JVM/Wasm/Native parts in future, jvm directory contains some jvm-specific things.

**Comment by ericvergnaud** [comment]
> > Well the package itself is org.antlr.v4.runtime.kotlin which I think is fine.
> 
> Not completely. Currently it doesn't matter a lot because packages will be reorginized when we implement KMP, but there is rule of good manners to keep in sync package name and directory structure and to get rid of `Package directive does not match the file location` warnings.
> 
> > We'd need to understand why this sits under src/jvm rather than directly under src ?
> 
> It helps us to separate JVM/Wasm/Native parts in future, jvm directory contains some jvm-specific things.

Well unless _everything_ is different between jvm/wasm (which would then question or choice of Kotlin), I'd rather have that distinction sit at the leaf level i.e. `org.antlr.v4.runtime.kotlin.jvm` (rather that the current `jvm.org...` structure)

**Comment by KvanTTT** [comment]
> Well unless everything is different between jvm/wasm (which would then question or choice of Kotlin)

I didn't say *everyting*, I'd say small number of things can be different and Kotlin handles such differences quite good thanks to [expect/actual declarations](https://kotlinlang.org/docs/multiplatform-expect-actual.html). You can explore `jvm` directory (as well as `wasmJsMain`, `nativeMain` and other) to figure out it contains almost nothing.

> I'd rather have that distinction sit at the leaf level i.e. org.antlr.v4.runtime.kotlin.jvm (rather that the current jvm.org... structure)

I agree, it looks more clear.

**Comment by ftomassetti** [comment]
I think it would be ideal to keep the same package name for the code under jvm but configure maven to recognize two different source directories: one for the common code and one for the JVM specific code. While this is trivial to do in Gradle and should be possible somehow in Maven, I cannot figure out how to do that, so I will just create the package `org.antlr.v4.runtime.kotlin.jvm` as suggested

**Comment by ftomassetti** [comment]
I have created the JVM specific package and rebased the commits on top of the current version of dev

**Review by KvanTTT — APPROVED** [review]

**Comment by KvanTTT** [comment]
@ericvergnaud are you ok with this PR?

**Comment by ericvergnaud** [comment]
Looks like there is still some work required in the remnants part, but that can be done later in a dedicated PR.

**Pull request merged**
