### PR TITLE
Fix failed tests caused by merging two MRs that affect each other a bit

### PR DESCRIPTION
**Pull request by KvanTTT**
https://github.com/antlr/antlr5/pull/30
https://github.com/antlr/antlr5/pull/31

### CODE REVIEW

**Comment by ericvergnaud** [comment]
Already fixed by #33

**Comment by KvanTTT** [comment]
But it should be merged at first and it's another change. You can rebase your branch on `dev` later.

**Comment by ericvergnaud** [comment]
> But it should be merged at first and it's another change. You can rebase your branch on `dev` later.

We don't have a product yet, so not sure we need to follow such a strict process during the initial phase of the project ?
I find it counterproductive. Once we have a product released, then we will definitely need to be much more accurate.

**Comment by ericvergnaud** [comment]
Already fixed, closing.

**Comment by KvanTTT** [comment]
> We don't have a product yet, so not sure we need to follow such a strict process during the initial phase of the project ? I find it counterproductive.

I don't find it's conuterproductive. The thing we don't have an agreement is much more couterproductive since it forces to develop different forks and not to coordinate resources.

**Pull request closed without merging**
